"use client";
import { useState } from "react";
import type { RecuperacaoLista } from "@/lib/reputacao-recuperacoes";

const ROTULO: Record<string,string> = { aberto:"Aberto", em_tratativa:"Em tratativa", resolvido:"Resolvido", atendimento:"Atendimento", tempo_espera:"Tempo de espera", comunicacao:"Comunicação", procedimento:"Procedimento", agendamento:"Agendamento", cobranca:"Cobrança", estrutura:"Estrutura", outro:"Outro" };
export function RecuperacoesExperiencia({ iniciais }: { iniciais: RecuperacaoLista[] }) {
  const [itens,setItens]=useState(iniciais); const [erro,setErro]=useState<string|null>(null);
  async function salvar(id:string, form:HTMLFormElement) { setErro(null); const fd=new FormData(form); const body={id,status:fd.get("status"),motivo:fd.get("motivo")||null,observacoesInternas:fd.get("observacoes"),solucao:fd.get("solucao")}; const r=await fetch("/api/reputacao/recuperacoes",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const json=await r.json() as {ok:boolean;error?:string}; if(!json.ok){setErro(json.error==="solucao_obrigatoria"?"Registre a solução antes de resolver.":"Não foi possível salvar o caso.");return;} setItens(x=>x.map(i=>i.id===id?{...i,status:body.status as RecuperacaoLista["status"],motivo:body.motivo as RecuperacaoLista["motivo"],observacoesInternas:String(body.observacoesInternas||"")||null,solucao:String(body.solucao||"")||null}:i)); }
  return <section className="space-y-3"><div><h2 className="text-xs font-medium uppercase tracking-wide text-neutral-500">Recuperação de experiência</h2><p className="mt-1 text-sm text-neutral-500">Trate rapidamente quem sinalizou que a experiência poderia melhorar.</p></div>{erro&&<p className="text-sm text-red-600">{erro}</p>}{itens.length===0?<p className="rounded-xl border border-neutral-200 bg-white px-4 py-8 text-center text-sm text-neutral-400">Nenhum caso de recuperação no período.</p>:itens.map(i=><form key={i.id} className="space-y-3 rounded-xl border border-neutral-200 bg-white p-4" onSubmit={e=>{e.preventDefault();void salvar(i.id,e.currentTarget)}}><div className="flex flex-wrap justify-between gap-2"><p className="font-medium text-neutral-900">{i.pacienteNome||"Paciente sem nome"}</p><span className="rounded-full bg-amber-50 px-2 py-0.5 text-xs font-medium text-amber-800">{ROTULO[i.status]}</span></div><blockquote className="border-l-2 border-neutral-200 pl-3 text-sm text-neutral-600">“{i.respostaOriginal}”</blockquote><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-neutral-600">Status<select name="status" defaultValue={i.status} className="mt-1 w-full rounded-lg border border-neutral-200 p-2 text-sm"><option value="aberto">Aberto</option><option value="em_tratativa">Em tratativa</option><option value="resolvido">Resolvido</option></select></label><label className="text-xs text-neutral-600">Motivo<select name="motivo" defaultValue={i.motivo??""} className="mt-1 w-full rounded-lg border border-neutral-200 p-2 text-sm"><option value="">A definir</option>{["atendimento","tempo_espera","comunicacao","procedimento","agendamento","cobranca","estrutura","outro"].map(v=><option key={v} value={v}>{ROTULO[v]}</option>)}</select></label></div><label className="block text-xs text-neutral-600">Observações internas<textarea name="observacoes" defaultValue={i.observacoesInternas??""} className="mt-1 w-full rounded-lg border border-neutral-200 p-2 text-sm" rows={2}/></label><label className="block text-xs text-neutral-600">Solução registrada<textarea name="solucao" defaultValue={i.solucao??""} className="mt-1 w-full rounded-lg border border-neutral-200 p-2 text-sm" rows={2}/></label><button className="rounded-lg bg-teal-700 px-3 py-1.5 text-sm font-medium text-white">Salvar caso</button></form>)}</section>;
}
